language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - 2.3.0
services:
  - redis-server
before_install: gem install bundler -v 1.10.6
script:
  - bundle exec rubocop
  - bundle exec rspec spec
