name: CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        ruby: [2.6, 2.7, 3.0]
        redis-version: [4, 5, 6]
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]') ||
      !contains(github.event.head_commit.message, '[skip ci]')

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Set up Redis ${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-${{ matrix.redis-version }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install -j $(getconf _NPROCESSORS_ONLN) --retry 3

      - name: Run RSspec
        run: bundle exec rspec --format documentation

      - name: Run Rubocop
        run: bundle exec rubocop
